mode: "dev"
dotenv: ".env/dev"

handlers:
  externalAPI:
    port: "8081"
    certFile: "./data/localhost.crt"
    keyFile: "./data/localhost.key"
    enableTLS: true
  internalAPI:
    port: "8083"
    certFile: "./data/localhost.crt"
    keyFile: "./data/localhost.key"
    enableTLS: true
  pprof:
    port: "8082"
    certFile: "./data/localhost.crt"
    keyFile: "./data/localhost.key"
    enableTLS: true

services:
  auth:
    authTokenTTL: 5
    refreshTokenTTL: 20160
    pubKeyFile: "./data/id_rsa.pub"
    pemKeyFile: "./data/id_rsa"

repositories:
  postgres:
    host: "127.0.0.1"
    port: "5471"
    username: "admin"
    db: "auth"
    sslmode: "disable"
    maxConnWaitingTime: 10
